---
galaxy_info:
  author: "Prometheus Community"
  description: "Prometheus Node Exporter"
  license: "Apache"
  min_ansible_version: "2.9"
  platforms:
    - name: "Ubuntu"
      versions:
        - "focal"
        - "jammy"
    - name: "Debian"
      versions:
        - "bullseye"
        - "buster"
    - name: "EL"
      versions:
        - "7"
        - "8"
        - "9"
    - name: "Fedora"
      versions:
        - "37"
        - "38"
    - name: "Rocky"
      versions:
        - "8.0"
        - "8.1"
        - "8.2"
        - "8.3"
        - "8.4"
        - "8.5"
        - "8.6"
        - "8.7"
        - "8.8"
        - "9.0"
        - "9.1"
        - "9.2"
  galaxy_tags:
    - "monitoring"
    - "prometheus"
    - "exporter"
    - "metrics"
    - "system"
